// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3OBbadtWIRA2vZRLBCLEhImimAewD1ho',
    appId: '1:9774258051:web:e829d0d5585195fe4408b6',
    messagingSenderId: '9774258051',
    projectId: 'smart-lamp-52cb7',
    authDomain: 'smart-lamp-52cb7.firebaseapp.com',
    databaseURL: 'https://smart-lamp-52cb7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-lamp-52cb7.firebasestorage.app',
    measurementId: 'G-YJ43ZEW9TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHHi_wRRCGd9zYrO5dTjXV78Go34kyu8o',
    appId: '1:9774258051:android:c11578d0163aa1624408b6',
    messagingSenderId: '9774258051',
    projectId: 'smart-lamp-52cb7',
    databaseURL: 'https://smart-lamp-52cb7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-lamp-52cb7.firebasestorage.app',
  );
}
